services:
  moviemap:
    build: .
    image: moviemap
    container_name: moviemap
    command: python scrape.py
    volumes:
      - .:/app
    working_dir: /app

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: film_locations
      DB_USER: film_locations_user
      DB_PASS: film_locations_pass
    volumes:
      - ./data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data/mongo-volume:/data/db
      - ./data/backups:/data/backups
    ports:
      - 27017-27019:27017-27019


volumes:
  mongo-data:

  
